name: learningflutter
description: "A new Flutter project."

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router: ^16.0.0
  flutter_svg: ^2.2.0
  
  # State Management
  provider: ^6.1.5
  riverpod: ^2.6.1
  flutter_riverpod: ^2.6.1
  
  # Deep Linking
  app_links: ^6.4.0
  url_launcher: ^6.3.1
  
  # File & PDF Handling
  file_picker: ^10.2.0
  path_provider: ^2.1.5
  syncfusion_flutter_pdfviewer: ^30.1.39
  permission_handler: ^12.0.1
  
  # Responsive Design
  flutter_screenutil: ^5.9.3
  responsive_framework: ^1.5.1
  
  # Animations & UI
  lottie: ^3.3.1
  shimmer: ^3.0.0
  flutter_staggered_animations: ^1.1.1
  
  # Storage
  shared_preferences: ^2.5.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Network
  dio: ^5.8.0
  connectivity_plus: ^6.1.4
  
  # Utils
  intl: ^0.20.2
  uuid: ^4.5.1
  path: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.5.4
  hive_generator: ^2.0.1


flutter:
  uses-material-design: true
  
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700