name: learningflutter
description: "A new Flutter project."

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  # go_router: ^16.0.0
  # flutter_svg: ^2.2.0
  # cached_network_image: ^3.4.1
  # # # State Management
  # # provider: ^6.1.5
  # riverpod: ^2.6.1
  # riverpod_annotation: ^2.6.1
  # retrofit: ^4.6.0
  # json_annotation: ^4.9.0
  # lottie: ^3.3.1
  # flutter_animate: ^4.5.2
  # shimmer: ^3.0.0
  # flutter_staggered_animations: ^1.1.1
  # pull_to_refresh: ^2.0.0
  # # # Storage
  # shared_preferences: ^2.5.3
  # flutter_secure_storage: ^9.2.4
  # hive: ^2.2.3
  # hive_flutter: ^1.1.0
  # flutter_slidable: ^4.0.0
  # flutter_form_builder: ^10.1.0
  # form_builder_validators: ^11.2.0
  # table_calendar: ^3.2.0
  # # # Network
  # dio: ^5.8.0
  # connectivity_plus: ^6.1.4
  # logger: ^2.6.0
  
  # # # Utils
  # intl: ^0.20.2
  # uuid: ^4.5.1
  # path: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true
  
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700